# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'CleverPet' do
pod 'JSONModel'
pod 'AFNetworking', '= 3.0.4'
pod 'AttributedMarkdown', :git => 'https://github.com/dreamwieber/AttributedMarkdown.git', :inhibit_warnings => true
pod 'OAStackView'
pod 'Intercom', '= 2.3.19'
pod 'GoogleIdentityToolkit', '= 1.1.3'
pod 'CHCSVParser', :inhibit_warnings => true
pod 'RBStoryboardLink', :inhibit_warnings => true
pod 'NMRangeSlider'
pod 'SparkSetup', :path => 'SparkSetup_Internal', :inhibit_warnings => true
pod 'Spark-SDK', :path => 'Spark-SDK_Internal'
pod 'BABCropperView', '= 0.4.6'
pod 'Firebase', '= 2.5.1'
pod 'FBSDKCoreKit', '= 4.10.0'
pod 'FBSDKShareKit', '= 4.10.0'
pod 'FBSDKLoginKit', '= 4.10.0'
pod 'CorePlot', '= 2.0'
pod 'SSKeychain'
pod 'Fabric'
pod 'Crashlytics'
pod 'OJFSegmentedProgressView', '~> 0.0.1'
pod 'Bolts', '= 1.6.0'
pod 'GoogleSymbolUtilities', '= 1.0.3'
pod 'GoogleAppUtilities', '= 1.0.0'
end
