# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'CleverPet' do
pod 'JSONModel'
pod 'AFNetworking'
pod 'AttributedMarkdown', :git => 'https://github.com/dreamwieber/AttributedMarkdown.git', :inhibit_warnings => true
pod 'OAStackView'
pod 'Intercom'
pod 'GoogleIdentityToolkit'
pod 'RBStoryboardLink', :inhibit_warnings => true
pod 'NMRangeSlider'
pod 'SparkSetup', :path => 'SparkSetup_Internal', :inhibit_warnings => true
pod 'Spark-SDK', :path => 'Spark-SDK_Internal'
pod 'BABCropperView'
pod 'Firebase', '>= 2.5.0'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'CorePlot', '~> 2.0'
pod 'SSKeychain'
pod 'Fabric'
pod 'Crashlytics'
pod 'Google/CloudMessaging'
pod 'OJFSegmentedProgressView', '~> 0.0.1'
end
