# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'CleverPet' do

pod 'GoogleIdentityToolkit'
pod 'CHCSVParser'
pod 'Spark-SDK', :git => 'https://github.com/dwrightffs/spark-sdk-ios.git', :branch => 'feature/access-token'
pod 'SparkSetup'

end

